[package]
name = "web_portal_lite"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"
serde = "1.0.137"
serde_yaml= "0.8.24"

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.2"
features = ["tera"]
